velodyne_driver_node:
  ros__parameters:
    device_ip: ""
    port: 2372
    model: "VLP16"
    frame_id: "velodyne"
    pcap: ""
    read_once: false
    read_fast: false
    rpm: 600.0
velodyne_transform_node:
  ros__parameters:
    model: "VLP16"
    calibration: ""
    min_range: 0.4
    max_range: 120.0
    frame_id: "velodyne"
    organize_cloud: false
    min_intensity: 25.5  # 0.1 * 255, matches script filterx